apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-cache
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-cache
  template:
    metadata:
      labels:
        app: metadata-cache
    spec:
      containers:
      - name: metadata-cache
        image: 992382695827.dkr.ecr.us-west-2.amazonaws.com/emilyhua/log-enhancement:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
      serviceAccountName: default


