apiVersion: v1
kind: Service
metadata:
  name: metadata-cache-service
  namespace: default
  labels:
    app: metadata-cache
spec:
  selector:
    app: metadata-cache
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051